[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[window]
blur = true
opacity = 0.7
decorations = 'Buttonless'

[window.padding]
x = 4
y = 8
